PUT http://localhost:3000/features/d7382126-25e3-4fe8-9b14-f1aa03919601
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxMmU2NjZjLTkxOGYtMTFmMS05YjcxLTc0ZTZlMjA5ZDJhMCIsInVzZXJuYW1lIjoiamhvbiIsImlhdCI6MTc4NjEwNzU3NCwiZXhwIjoxNzg2MTkzOTc0fQ.cVs_ITShfJX5YI7aEVdUHdS-vuk-NZcDrfXM9qD3Qss
Content-Type:application/json

{
    "title":"New Login",

    "priority":"Medium"
}